* Engaging with Math
   
Studying mathematics requires a certain discipline and habits.
It's not hard to develop these, but if you don't, you won't learn as much
and you'll probably get lost.  Here's what has helped me:

  * Write stuff down!  This is easy, and surprisingly effective.
  * Do the exercises.  Really try.  Don't just look at the answers.
  * Keep to a schedule.  Make some time every day to do exercises.

But just don't take my word for it:

The [[https://pimbook.org/pdf/pim_first_pages.pdf][first pages of A Programmer's Introduction to Mathematics]]
explains that programmers tend to have different habits
than mathematicians, and has very good advice on how to gain
the discipline you need.

[[http://math.ucr.edu/home/baez/books.html][How to learn math and physics]] is John Baez's extremely well-informed advice.


** Approachable Math Presentations
   
   Here are some phenomenal explainers of math topics at introductory levels.
   
  * [[https://www.math3ma.com/][Tai-Danae Bradley]] ([[https://twitter.com/math3ma?s=03][twitter]])
  * [[https://jeremykun.com/][Jeremy Kun]]
