* Engaging with Math
   
Studying mathematics requires a certain discipline and habits.
It's not hard to develop these, but if you don't, you won't learn as much
and you'll probably get lost.  Here's what has helped me:

  * Write stuff down!  This is easy, and surprisingly effective.
  * Do the exercises.  Really try.  Don't just look at the answers.
  * Keep to a schedule.  Make some time every day to do exercises.

But just don't take my word for it:

The [[https://pimbook.org/pdf/pim_first_pages.pdf][first pages of A Programmer's Introduction to Mathematics]]
explains that programmers tend to have different habits
than mathematicians, and has very good advice on how to gain
the discipline you need.

[[http://math.ucr.edu/home/baez/books.html][How to learn math and physics]] is John Baez's extremely well-informed advice.

[[https://teachyourselfcs.com/][Teach Yourself CS]] recommends good books and courses on not just math,
but also computer architecture, programming, and distributed systems.

** Leslie Lamport: Coding is only a small part of programming

   Abstracted by [[https://twitter.com/ultrasaurus/status/1201447302444924934?s=03][Sarah Allen]]:
   
[[https://www.zmescience.com/science/difference-programming-coding-15112019/amp/][The Difference Between Programming and Coding]]
   * [[https://www.youtube.com/watch?v=de7Id8sKQzY][Lamport video 1]] (7:26)
   * [[https://www.youtube.com/watch?v=36tsSOFRMjM][Lamport video 2]] (1:43)
“You don’t understand something until you’ve written it down carefully —
carefully enough to explain it to somebody else. And if you haven’t done that,
you’re just thinking you understand it,” Lamport, ⁦@HLForum⁩ 2019

“... Think of it this way: writing is a way of revealing how fuzzy your thinking
is. In this context, coding is just a small part of programming where real
thinking takes place.”

** Approachable Math Presentations
   
   Here are some phenomenal explainers of math topics at introductory levels.
   
  * [[https://www.math3ma.com/][Tai-Danae Bradley]] ([[https://twitter.com/math3ma?s=03][twitter]])
  * [[https://jeremykun.com/][Jeremy Kun]]
