* ACT Study Group week 1
   
** preparation
   
   * Read Seven Sketches preface and section 1.1

   * Do Exercises 1.1 thru 1.4

  [[https://forum.azimuthproject.org/discussion/1807/lecture-1-introduction][Baez Lecture 1]] deals mostly with the mechanics of how that course was run.
  You can safely skip it.
  
  [[https://forum.azimuthproject.org/discussion/1808/lecture-2-what-is-applied-category-theory#Head][Baez Lecture 2]] What is applied category theory?

  [[https://forum.azimuthproject.org/discussion/1718/chapter-1/p1][Baez Discussions on Chapter 1]].  Try the Puzzles.

  
** goals

This week we want to outline what ACT is and why you might want to study it.
   * You'll know where to find study materials.
   * You'll find a research paper on a topic that you'd like to learn about.
     This will
      * help the group understand what topics interest its members
      * motivate your study -- it's good to have a goal in mind



I'll echo [[https://forum.azimuthproject.org/discussion/1807/lecture-1-introduction][John Baez's intro to his ACT course]].
#+begin_quote
So, your job is to read the book, ask questions, try to do the Exercises and
Puzzles, write your answers here - and most importantly, discuss everything to
death! There's a place to discuss each Chapter, and a place to discuss each
Lecture, and these discussions can go on indefinitely.

I will take part in these discussions - that's what I love about online forums.
But if all of you ask lots of questions - and I really hope you do! - I'll be
unable to answer them all myself. So, it's crucial that if someone asks a
question, and you think you know the answer, help them out.

With luck, we'll all learn a lot of stuff, make a lot of new friends... and some
of us will go ahead to revolutionize human thought, invent amazing new
technologies, and save the planet.
#+end_quote

Please note that unlike John Baez, I'm still learning this material myself,
so I'm relying heavily on more knowledgeable members to help.

[[https://forum.azimuthproject.org/discussion/1812/lecture-3-chapter-1-posets/p1][Baez Lecture 3]] Posets


** week 1 assignment (for week 2)

   * Read [[file:engaging.org][Engaging with Mathematics]], especially if you're a programmer.

   * Read Seven Sketches section 1.2. Do exercises 1.6 thru 1.74 (there aren't
     68 exercises! The numbering includes definitions and examples).

   * Find a research paper on a topic that interests you.
     The long list has a bunch, but search the internet if you like.
     
     It's ok if you can't understand the paper yet, but try to find
     one that you can "almost understand".
     As we progress through the book, you will understand more and more of it.

     This will
      * help the group understand what topics interest its members
      * motivate your study -- it's good to have a goal in mind

Optional, but highly recommended:

Listen to [[https://corecursive.com/035-bartosz-milewski-category-theory/][Bartosz Milewski on Category Theory in Programming]].

Read [[https://arxiv.org/pdf/1809.05923.pdf][What is Applied Category Theory?]] and [[https://www.math3ma.com/blog/what-is-category-theory-anyway][What is Category Theory Anyway?]].

